module.exports = [
  {value: 'AMP', name: 'AMP (Synereo AMP)'},
  {value: 'ARDR', name: 'ARDR (Ardor)'},
  {value: 'BCN', name: 'BCN (Bytecoin)'},
  {value: 'BCY', name: 'BCY (BitCrystals)'},
  {value: 'BELA', name: 'BELA (Belacoin)'},
  {value: 'BLK', name: 'BLK (BlackCoin)'},
  {value: 'BTCD', name: 'BTCD (BitcoinDark)'},
  {value: 'BTM', name: 'BTM (Bitmark)'},
  {value: 'BTS', name: 'BTS (BitShares)'},
  {value: 'BURST', name: 'BURST (Burst)'},
  {value: 'CLAM', name: 'CLAM (CLAMS)'},
  {value: 'DASH', name: 'DASH (Dash)'},
  {value: 'DCR', name: 'DCR (Decred)'},
  {value: 'DGB', name: 'DGB (DigiByte)'},
  {value: 'DOGE', name: 'DOGE (Dogecoin)'},
  {value: 'EMC2', name: 'EMC2 (Einsteinium)'},
  {value: 'ETC', name: 'ETC (Ethereum Classic)'},
  {value: 'ETH', name: 'ETH (Ethereum)'},
  {value: 'EXP', name: 'EXP (Expanse)'},
  {value: 'FCT', name: 'FCT (Factom)'},
  {value: 'FLDC', name: 'FLDC (FoldingCoin)'},
  {value: 'FLO', name: 'FLO (Florincoin)'},
  {value: 'GAME', name: 'GAME (GameCredits)'},
  {value: 'GNO', name: 'GNO (Gnosis)'},
  {value: 'GNT', name: 'GNT (Golem)'},
  {value: 'GRC', name: 'GRC (Gridcoin Research)'},
  {value: 'HUC', name: 'HUC (Huntercoin)'},
  {value: 'LBC', name: 'LBC (LBRY Credits)'},
  {value: 'LSK', name: 'LSK (Lisk)'},
  {value: 'LTC', name: 'LTC (Litecoin)'},
  {value: 'MAID', name: 'MAID (MaidSafeCoin)'},
  {value: 'NAUT', name: 'NAUT (Nautiluscoin)'},
  {value: 'NAV', name: 'NAV (NAVCoin)'},
  {value: 'NEOS', name: 'NEOS (Neoscoin)'},
  {value: 'NMC', name: 'NMC (Namecoin)'},
  {value: 'NOTE', name: 'NOTE (DNotes)'},
  {value: 'NXC', name: 'NXC (Nexium)'},
  {value: 'NXT', name: 'NXT (NXT)'},
  {value: 'OMNI', name: 'OMNI (Omni)'},
  {value: 'PASC', name: 'PASC (PascalCoin)'},
  {value: 'PINK', name: 'PINK (Pinkcoin)'},
  {value: 'POT', name: 'POT (PotCoin)'},
  {value: 'PPC', name: 'PPC (Peercoin)'},
  {value: 'RADS', name: 'RADS (Radium)'},
  {value: 'REP', name: 'REP (Augur)'},
  {value: 'RIC', name: 'RIC (Riecoin)'},
  {value: 'SBD', name: 'SBD (Steem Dollars)'},
  {value: 'SC', name: 'SC (Siacoin)'},
  {value: 'SJCX', name: 'SJCX (Storjcoin X)'},
  {value: 'STEEM', name: 'STEEM (STEEM)'},
  {value: 'STR', name: 'STR (Stellar)'},
  {value: 'STRAT', name: 'STRAT (Stratis)'},
  {value: 'SYS', name: 'SYS (Syscoin)'},
  {value: 'VIA', name: 'VIA (Viacoin)'},
  {value: 'VRC', name: 'VRC (VeriCoin)'},
  {value: 'VTC', name: 'VTC (Vertcoin)'},
  {value: 'XBC', name: 'XBC (BitcoinPlus)'},
  {value: 'XCP', name: 'XCP (Counterparty)'},
  {value: 'XEM', name: 'XEM (NEM)'},
  {value: 'XMR', name: 'XMR (Monero)'},
  {value: 'XPM', name: 'XPM (Primecoin)'},
  {value: 'XRP', name: 'XRP (Ripple)'},
  {value: 'XVC', name: 'XVC (Vcash)'},
  {value: 'ZEC', name: 'ZEC (Zcash)'}];
